---
- hosts: proxmox
  become: yes

  vars:
    qbittorrent_version: 4.5.2
    homeassistant_version: 2023.5.6
    kerberos_version: 2023.5.1
    immich_version: 1.7.0
    scrutiny_version: 0.9.0

  tasks:
    # ... (previous tasks)

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create Nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/services.conf
      notify: Restart Nginx

    - name: Create static services page
      template:
        src: services.html.j2
        dest: /var/www/html/index.html

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
