version: '3'
services:
  homeassistant:
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      DISABLE_JEMALLOC: true
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
