version: '3'

services:

  jira:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - JIRA_HOME=/var/atlassian/jira
      - CATALINA_OPTS=-Xms2048m -Xmx4096m -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+ExitOnOutOfMemoryError
      - JDBC_URL=jdbc:postgresql://db:5432/jira
      - JDBC_USER=jira_software
      - JDBC_PASSWORD=78XqTFwJBgULQnuc
#      - JMX_REMOTE_AUTH_PASSWORD=your_secure_jmx_password
#      - JMX_REMOTE_AUTH_USERNAME=jmx_user
#      - JMX_REMOTE_PORT=9999
#      - JMX_REMOTE_SSL=false
    volumes:
      - jira-home:/var/atlassian/jira
      - jira-logs:/opt/atlassian/jira/logs
      - ./setup-database.sh:/setup-database.sh
    depends_on:
      - db

    entrypoint: ["/bin/bash", "-c", "
      /opt/atlassian/jira/bin/start-jira.sh &
      sleep 15
      /setup-database.sh
      "]
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=jira
      - POSTGRES_USER=jira_software
      - POSTGRES_PASSWORD=78XqTFwJBgULQnuc
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
        
    volumes:
      - jira-db:/var/lib/postgresql/data

volumes:
  jira-home:
  jira-db:
  jira-logs:
