FROM atlassian/jira-software:9.12.1

# Установите необходимые зависимости
RUN apt-get update && apt-get install -y \
    curl \
    jq \
    openjdk-11-jdk \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Скопируйте скрипты и atlassian-agent.jar
COPY get_server_id.sh /opt/atlassian/jira/bin/get_server_id.sh
COPY activate_jira.sh /opt/atlassian/jira/bin/activate_jira.sh
COPY restore_jira.sh /opt/atlassian/jira/bin/restore_jira.sh
COPY atlassian-agent.jar /opt/atlassian/atlassian-agent.jar
RUN chmod +x /opt/atlassian/jira/bin/get_server_id.sh /opt/atlassian/jira/bin/activate_jira.sh /opt/atlassian/jira/bin/restore_jira.sh

# Сохраните Server ID в файл
RUN /opt/atlassian/jira/bin/get_server_id.sh > /opt/atlassian/jira/server_id.txt

# Установите переменные окружения для активации и восстановления
ENV JIRA_ADMIN_EMAIL=your_admin_email
ENV JIRA_ADMIN_PASSWORD=your_admin_password
ENV JIRA_BACKUP_FILE=/opt/atlassian/jira/backup.zip

# Запустите скрипт восстановления или активации при запуске контейнера
CMD ["/opt/atlassian/jira/bin/restore_jira.sh", "/opt/atlassian/jira/bin/activate_jira.sh"]
