version: '3'

services:

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/etc/traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=your_email@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json

volumes:
  traefik-data:
